### ISSUE TITLE
Link to docs doesnt work

### ISSUE THREAD

**Issue by totty90** [figurebelow/trendyways#1]
You should have this link instead: http://htmlpreview.github.io/?https://github.com/figurebelow/trendyways/blob/master/docs/index.html

Or something similar that renders the html.

**Comment by figurebelow** [comment]
Thanks, I fixed that.
Btw HTMLPreview tool is pretty cool.

**Comment by kayazinc** [comment]
Hi @figurebelow, I still unable to render the documentation proper, it is blank.

**Comment by figurebelow** [comment]
Do you mean the link http://htmlpreview.github.io/?https://github.com/figurebelow/trendyways/blob/master/docs/index.html or the docs after cloning the repo?

**Comment by kayazinc** [comment]
I meant https://github.com/figurebelow/trendyways/blob/master/docs/index.html
When I clicked on any of the links, I will see a empty page:
![screenshot - nov 23 2016 10 02 am](https://cloud.githubusercontent.com/assets/19774010/20549070/09b0b88a-b164-11e6-8482-0cb3d34a183b.png)

**Comment by figurebelow** [comment]
The problem seems to be in the preview tool used for that, I've changed it to https://cdn.rawgit.com/figurebelow/trendyways/master/docs/index.html , which seems to render the html fine.

**Comment by kayazinc** [comment]
Yeah it works, thanks!
